### ISSUE TITLE
Wrong instructions

### ISSUE THREAD

**Issue by tomsbergmanis** [mahfuzibnalam/terminology_evaluation#2]
`python3 evaluate_term_wmt.py \
    --language fr \
    --hypothesis data/en-fr.dev.txt.truecased.xml \
    --source_ref_directory data/dev.en-fr.en.xml \
    --target_ref_directory data/dev.en-fr.fr.xml \`
    is not in line with your code:
```
usage: evaluate_term_wmt.py [-h] [--language LANGUAGE]
                                     [--hypothesis HYPOTHESIS]
                                     [--source SOURCE]
                                     [--target_reference TARGET_REFERENCE]
                                     [--BLEU BLEU] [--EXACT_MATCH EXACT_MATCH]
                                     [--WINDOW_OVERLAP WINDOW_OVERLAP]
                                     [--MOD_TER MOD_TER] [--TER TER]

```

**Comment by mahfuzibnalam** [comment]
We were updating our script which is why readme was a little behind. We have changed a lot in the script. Can you please start from the beginning and see everything is okay. If not please let us know.
