### ISSUE TITLE
What license is the code available under?

### ISSUE THREAD

**Issue by TommiNieminen** [mahfuzibnalam/terminology_evaluation#5]
Hi,

I'm the developer of OPUS-CAT (https://github.com/Helsinki-NLP/OPUS-CAT), a collection of MT software aimed at professional translators. I'm currently working on implementing terminology support, and as a preliminary step, I'm going to add a functionality for evaluating terminological accuracy. I would like to use your script as the basis for that functionality, but I can't find any licensing information for it. OPUS-CAT uses MIT license, so I'd like to know whether it is possible to use **terminology_evaluation** as part of MIT licensed software?

-Tommi

**Comment by mahfuzibnalam** [comment]
I have added an MIT license. You can use whatever you want.

**Comment by TommiNieminen** [comment]
Great, thanks for sharing this script, it saves a lot of work.
